login_login_homepage:
    path:     /login
    defaults: { _controller: LoginLoginBundle:Default:index }

login_login_signup:
    path:     /signup
    defaults: { _controller: LoginLoginBundle:Default:signup }