<?php

namespace Meridian\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameQuestionRepository extends EntityRepository
{
}
