welcome_page:
    path:   /welcome
    defaults: { _controller: MeridianUserBundle:Default:index }

start_page:
    path:   /
    defaults: { _controller: MeridianUserBundle:Default:start }

score_test:
    path: /welcome/score
    defaults: { _controller: MeridianCoreBundle:Proxy:getScores }

score_demo:
    path: /demo/score
    defaults: { _controller: MeridianCoreBundle:Proxy:getDemoScores }

about:
    path:   /about
    defaults: { _controller: MeridianUserBundle:Default:about }
