meridian_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: MeridianUserBundle:Default:index }




welcome_page:
    path:   /welcome
    defaults: { _controller: MeridianUserBundle:Default:index }

start_page:
    path:   /
    defaults: { _controller: MeridianUserBundle:Default:start }