meridian_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: MeridianUserBundle:Default:index }


welcome_page:
    path:   /welcome
    defaults: { _controller: MeridianUserBundle:Default:index }

start_page:
    path:   /
    defaults: { _controller: MeridianUserBundle:Default:start }

score_test:
    path: /welcome/score
    defaults: { _controller: MeridianCoreBundle:Proxy:getScores }

score_max:
    path: /demo/score
    defaults: { _controller: MeridianCoreBundle:Proxy:getMaxScores }

about:
    path:   /about
    defaults: { _controller: MeridianUserBundle:Default:about }
