services:
#    meridian_user.example:
#        class: Meridian\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    acme_user.profile.form.type:
        class: Meridian\UserBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: test_user_profile }