meridian_core_homepage:
    path:     /hello/{name}
    defaults: { _controller: MeridianCoreBundle:Default:index }
meridian_core_form:
    path:     /newQuestion
    defaults: { _controller: MeridianCoreBundle:Default:newFormForQuestion }
meridian_core_questions:
    path:     /questions
    defaults: { _controller: MeridianCoreBundle:Default:getAllQuestions }
meridian_core_question_remove:
    path:     /removeQuestion/{id}
    defaults: { _controller: MeridianCoreBundle:Default:removeOneQuestion }
meridian_core_question_edit:
    path:     /questionEdit/{id}
    defaults: { _controller: MeridianCoreBundle:Default:editQuestion }
meridian_core_get_answer:
    path:     /answer/{id}
    defaults: { _controller: MeridianCoreBundle:Default:getAnswerForQuestion }
meridian_core_test:
    path:     /test
    defaults: { _controller: MeridianCoreBundle:Default:getMainForm }
meridian_core_demo:
    path:     /demo
    defaults: { _controller: MeridianCoreBundle:Demo:startGame }
meridian_core_demo_question_default:
      path:     /demo/question
      defaults: { _controller: MeridianCoreBundle:Demo:getDemoGame }
meridian_core_demo_question:
    path:     /demo/question/{game_id}/{question_id}
    defaults: { _controller: MeridianCoreBundle:Demo:getDemoGame }
#meridian_core_demo_question:
 #   path:     /demo/question/{game_id}
  #  defaults: { _controller: MeridianCoreBundle:Demo:getQuestionByGameId }
