meridian_core_admin_expo:
    resource: "@MeridianCoreBundle/Resources/config/routing/expo.yml"
    prefix:   /admin/expo

meridian_core_homepage:
    path:     /hello/{name}
    defaults: { _controller: MeridianCoreBundle:Default:index }
meridian_core_form:
    path:     /admin/newquestion
    defaults: { _controller: MeridianCoreBundle:Default:getMainForm }
meridian_core_questions:
    path:     /admin/questions
    defaults: { _controller: MeridianCoreBundle:Default:getAllQuestions }
meridian_core_question_remove:
    path:     /admin/removequestion/{id}
    defaults: { _controller: MeridianCoreBundle:Default:removeOneQuestion }
meridian_core_question_edit:
    path:     /admin/editquestion/{id}
    defaults: { _controller: MeridianCoreBundle:Default:editQuestion }
meridian_core_answer_edit:
    path:     /admin/editanswer/{id}
    defaults: { _controller: MeridianCoreBundle:Default:editAnswer }
meridian_core_demo_default:
    path:     /demo
    defaults: { _controller: MeridianCoreBundle:Demo:getDemoGame }
meridian_core_demo_question:
      path:     /demo/{gameId}/{questionId}
      defaults: { _controller: MeridianCoreBundle:Demo:getDemoGame, gameId:1, questionId:1 }


meridian_core_game:
      path:     /game
      defaults: { _controller: MeridianCoreBundle:Default:startGame }


expo:
    path:   /naujienos
    defaults: { _controller: MeridianCoreBundle:Expo:expo }


expo_update:
    path:   /admin/update_expo
    defaults: { _controller: MeridianCoreBundle:Expo:updateExpo }
