services:
    meridian_core.demoservices:
        class: Meridian\CoreBundle\Service\demoServices
        arguments: ["@doctrine.orm.entity_manager", "@form.factory"]
    meridian_core.questionanswerservices:
        class: Meridian\CoreBundle\Service\QuestionAnswerService
        arguments: ["@doctrine.orm.entity_manager", "@form.factory"]